### ISSUE TITLE
Invalid conversion from ´int´ ... during build on arduino 1.8.8

### ISSUE THREAD

**Issue by cmoeg** [HelTecAutomation/ESP32_LoRaWAN#5]
Issue occures during build process.

May be there is wrong library used.
But there are a lot of libraries available, so perhaps mention in readme the used ones,..

error mesage below:

Arduino: 1.8.8 (Windows 10), Board: "Heltec_WIFI_LoRa_32, 80MHz, 921600"
OTAA_DHT11:79:41: error: invalid conversion from 'int' to 'OLEDDISPLAY_GEOMETRY' [-fpermissive] SSD1306  display(0x3c, SDA, SCL, RST_LED);
                                         ^
In file included from \Documents\Arduino\libraries\ESP8266_and_ESP32_Oled_Driver_for_SSD1306_display\src/SSD1306.h:33:0,
                from \ESP32_LoRaWAN-master\examples\OTAA_DHT11\OTAA_DHT11.ino:49:

\Documents\Arduino\libraries\ESP8266_and_ESP32_Oled_Driver_for_SSD1306_display\src/SSD1306Wire.h:45:5: note:   initializing argument 4 of 'SSD1306Wire::SSD1306Wire(uint8_t, uint8_t, uint8_t, OLEDDISPLAY_GEOMETRY)'

     SSD1306Wire(uint8_t _address, uint8_t _sda, uint8_t _scl, OLEDDISPLAY_GEOMETRY g = GEOMETRY_128_64) {

     ^

\ESP32_LoRaWAN-master\examples\OTAA_DHT11\OTAA_DHT11.ino: In function 'void LEDdisplayJOINING()':

OTAA_DHT11:88:11: error: 'SSD1306 {aka class SSD1306Wire}' has no member named 'wakeup'

   display.wakeup();

           ^

\ESP32_LoRaWAN-master\examples\OTAA_DHT11\OTAA_DHT11.ino: In function 'void LEDdisplayJOINED()':

OTAA_DHT11:97:11: error: 'SSD1306 {aka class SSD1306Wire}' has no member named 'wakeup'

   display.wakeup();

           ^

OTAA_DHT11:102:11: error: 'SSD1306 {aka class SSD1306Wire}' has no member named 'sleep'

   display.sleep();

           ^

ESP32_LoRaWAN-master\examples\OTAA_DHT11\OTAA_DHT11.ino: In function 'void LEDdisplaySENDING()':

OTAA_DHT11:109:11: error: 'SSD1306 {aka class SSD1306Wire}' has no member named 'wakeup'

   display.wakeup();

           ^

\ESP32_LoRaWAN-master\examples\OTAA_DHT11\OTAA_DHT11.ino: In function 'void LEDdisplayACKED()':

OTAA_DHT11:128:11: error: 'SSD1306 {aka class SSD1306Wire}' has no member named 'sleep'

   display.sleep();

           ^

\ESP32_LoRaWAN-master\examples\OTAA_DHT11\OTAA_DHT11.ino: In function 'void LEDdisplaySTART()':

OTAA_DHT11:133:11: error: 'SSD1306 {aka class SSD1306Wire}' has no member named 'wakeup'

   display.wakeup();

           ^

exit status 1
invalid conversion from 'int' to 'OLEDDISPLAY_GEOMETRY' [-fpermissive]

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by Heltec-Aaron-Lee** [comment]
Hi @cmoeg , it's because we updated the [Heltec ESP32 development environment](https://docs.heltec.cn/#/en/user_manual/how_to_install_esp32_Arduino), we had fixed the bug now.
